VMO-2565 update contact to support contact properties
FLOIP/flow-runner pull request #15
Opened 2020-08-21 15:17 UTC by GrimFunction

2020-08-27 19:56 UTC, AlteaDown requested changes

2020-08-27 19:56 UTC, AlteaDown commented on src/flow-spec/Contact.ts
> +  [key: string]: IContactProperty | ((...args: any[]) => IContactProperty | undefined) | string |undefined
minor formatting: `|undefined` should be `| undefined`

2020-08-27 19:56 UTC, AlteaDown commented on src/flow-spec/Contact.ts
> +  id!: string
`id` comes after `[key: string]`, but id is a `[key: string]` (and after it as well). I wonder if this makes it so id can never be resolved.

2020-08-27 19:56 UTC, AlteaDown commented on src/flow-spec/ContactProperty.ts
> +  createdAt: string = new Date().toISOString().replace('T', ' ')
You should use `createFormattedDate()` so that we are referencing the same conversion everywhere, in case we decided to change it (and I really hope we do at some point)

2020-08-27 19:56 UTC, AlteaDown commented on src/flow-spec/Contact.ts
> +  [key: string]: IContactProperty | ((...args: any[]) => IContactProperty | undefined) | string |undefined
Maybe this type definition should be a type, so it's easier to reference?

2020-08-27 20:03 UTC, GrimFunction commented on src/flow-spec/Contact.ts
> +  id!: string
In VMO-2566, I didn't have any problem assigning or retrieving "id" as a string even with the existence of index properties.

2020-08-28 20:31 UTC, AlteaDown approved these changes

2020-08-28 20:33 UTC, seifertk approved these changes
Approved pending changes that @AlteaDown mentioned.

2020-08-28 20:42 UTC, merged